package com.example.huoshangkou.jubowan.db.chatdb;

import com.example.huoshangkou.jubowan.db.ChatBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatBeanDaoConfig;

    private final ChatBeanDao chatBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatBeanDaoConfig = daoConfigMap.get(ChatBeanDao.class).clone();
        chatBeanDaoConfig.initIdentityScope(type);

        chatBeanDao = new ChatBeanDao(chatBeanDaoConfig, this);

        registerDao(ChatBean.class, chatBeanDao);
    }
    
    public void clear() {
        chatBeanDaoConfig.getIdentityScope().clear();
    }

    public ChatBeanDao getChatBeanDao() {
        return chatBeanDao;
    }

}
